[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rtd-tutorial"
authors = [{name = "Meen Chul Kim", email = "meenchulkim@meenchulkim.com"}]
dynamic = ["version", "description"]
